template: |
  # What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
name-template: "Version $RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"

version-resolver:
  major:
    labels:
      - "release-major"
  minor:
    labels:
      - "release-minor"
  patch:
    labels:
      - "release-patch"
  default: patch

autolabeler:
  - label: "release-major"
    title:
      - "/^BREAKING CHANGE:/"
  - label: "release-minor"
    title:
      - "/^feat:/"
      - "/^feat\\(.+\\):/"
