version: '3.4'

services:
  http-header-authenticator:
    image: http-header-authenticator
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      HEADER: 'X-test-secret'
      VALUE: 'changeme'
    ports:
      - 8080:8080
