apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  HEADER: {{ .Values.securityHeader.name | default "X-Auth-Token" | b64enc }}
  VALUE: {{ .Values.securityHeader.value | default "1234567890"   | b64enc }}
