name: Internal - Common Continuous Integration tasks

on:
  workflow_call:

jobs:

  golangci-lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.21'
      - name: Run linters
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54

  go-test:
    strategy:
      matrix:
        go-version: ['1.21']
        platform: [self-hosted]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5.0.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: go test ./... -v -covermode=count

  go-coverage:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.21'
      - name: Calc coverage
        run: |
          go test ./... -v -covermode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
        with:
          version: v1.0.6
      - name: Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.github_token }}
          file: coverage.lcov
          allow-empty: true

  ct-lint:
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install tools with asdf
      - name: Install tools with asdf
        uses: asdf-vm/actions/install@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.9.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
