name: Internal - Common Continuous Integration tasks

on:
  workflow_call:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21'
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

  test:
    strategy:
      matrix:
        go-version: ['1.21']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        if: success()
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: go test ./... -v -covermode=count

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        if: success()
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21'
      - name: Calc coverage
        run: |
          go test ./... -v -covermode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
        with:
          version: v1.0.6
      - name: Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.github_token }}
          file: coverage.lcov
