name: Main - Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  ci:
    name: Continuous Integration
    uses: ./.github/workflows/__shared-ci.yml
    secrets: inherit

  update_release_draft:
    # we want to publish a new tag only if ci succeeds
    needs: ci
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true
          disable-autolabeler: true
