name: Main - Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  ci:
    name: Continuous Integration
    uses: ./.github/workflows/__shared-ci.yml
    secrets: inherit

  docker-build-images:
    name: Docker Build Images
    needs: ci
    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@0.14.4
    secrets:
      oci-registry-password: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}
    with:
      runs-on: '["self-hosted"]'
      oci-registry: "docker.io"
      oci-registry-username: ${{ vars.DOCKERHUB_REGISTRY_USERNAME }}
      images: |
        [{
          "image": "http-header-authenticator",
          "dockerfile": "./Dockerfile",
          "platforms": [
            "linux/amd64",
            "linux/arm64"
          ]
        }]

  update_release_draft:
    # we want to publish a new tag only if ci succeeds
    needs: ci
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true
          disable-autolabeler: true
