name: Main - Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  ci:
    name: Continuous Integration
    uses: ./.github/workflows/__shared-ci.yml
    secrets: inherit
