name: Pull request - Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:

  pull-request-labeler:
    name: Pull request labeler
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disable-releaser: true

  ci:
    name: Continuous Integration
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - uses: ./.github/workflows/__shared-ci.yml
        secrets: inherit
